on:
  push:
    branches: '**'   # [ "main" ]
  pull_request:
    branches: '**'   # [ "main" ]

jobs:
  SendJSONData:

    runs-on: ubuntu-latest
    
    steps:
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: '#general'
          # This data can be any valid JSON from a previous step in the GitHub Action
          payload: |
            { 
              "text": "*Code Coverage Task * - redefined",
            	"blocks": [
                      {
                          "type": "section",
                          "text": {
                              "type": "mrkdwn",
                              "text": "Hi Pay-Pay :wave:"
                          }
                      },
                      {
                          "type": "section",
                          "text": {
                              "type": "mrkdwn",
                              "text": "Varun this works! App helps you to stay up-to-date with your meetings and events right here within Slack. These are just a few things which you will be able to do:"
                          }
                      },
                      {
                          "type": "section",
                          "text": {
                              "type": "mrkdwn",
                              "text": "• Slack Web Hook  \n • Slack Github Actions \n • Gradle Tasks to communicate to Slack with curl cmd"
                          }
                      },
                      {
                          "type": "section",
                          "text": {
                              "type": "mrkdwn",
                              "text": "But before you can do all these amazing things, we need you to connect your Slack Channel to see the changes in App."
                          }
                      },
                  ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
