on:
  pull_request:
  push:
    branches:
      - '**'

jobs:
  
  integration_test_botToken:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Post message to Slack via botToken
      id: slackToken
      uses: ./
      with:
        channel-id: "C05L0RYE6MT"
        slack-message: 'CI Post from slack-send GitHub Action! Succeeded!!'
        # payload: "{\"key\":\"value\",\"foo\":\"bar\"}"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_SECRET_KEY }}
        
