on: [push]

jobs:
  new_push_job:
    runs-on: ubuntu-latest
    name: New push to repo
    steps:
    - name: Send GitHub trigger payload to Slack Workflow Builder
      id: slackPayloadFile
      uses: ./
      with:
        payload-file-path: ./resources/payload-notification.json
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        JOB_STATUS: ${{ job.status }}
        ATTACHMENT_COLOR: ${{ (job.status == 'success' && 'good') || (job.status == 'failure' && 'danger') || 'warning' }}
