on:
  push:
    branches: '**'   # [ "main" ]
  pull_request:
    branches: '**'   # [ "main" ]

jobs:
  integration_test_file_payload:
    runs-on: ubuntu-latest
    steps:
    - uses: slackapi/slack-github-action@v1.24.0
    - name: Post message to Slack with Payload path
      id: slackPayloadFile
      uses: ./
      slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
      with:
        payload-file-path: /home/runner/work/_temp/_github_workflow/small_payload.json
      
      env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
