on:
  push:
    branches: '**'   # [ "main" ]
  pull_request:
    branches: '**'   # [ "main" ]

jobs:

  test-json-data:
    runs-on: ubuntu-latest

    steps:
      - name: send json payload
        id: slack-notify-action
        uses: slackapi/slack-github-action@v1.24.0

        with:
          # block kit payload
          payload: "{\"text\":\"Incoming Webhook test for slack send\", \"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"plain_text\",\"text\":\"A post by Slack Send GitHub Action. Testing Incoming webhooks\",\"emoji\":true}}]}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

        # Use the output from the `slackIncoming` step
      - name: Check Action output is not empty
        run: test -n "${{ steps.slack-notify-action.outputs.time }}"

  json-payload-path:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - run: npm ci && npm run build
      - name: Dump out GitHub Context
        run: echo $JSON
        env:
          JSON: ${{ toJSON(github) }}
      - name: Post message to Slack with Payload path
        id: slackPayloadFile
        uses: ./
        with:
          payload-file-path: ./.github/payload.json
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
          JOB_STATUS: ${{ job.status }}
          ATTACHMENT_COLOR: ${{ (job.status == 'success' && 'good') || (job.status == 'failure' && 'danger') || 'warning' }}
  
      # Use the output from the `slackIncoming` step
      - name: Check Action output is not empty
        run: test -n "${{ steps.slackPayloadFile.outputs.time }}"

      
  send-json-data-slack-payload-path:

    runs-on: ubuntu-latest
    
    steps:
      - name: Send Json data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
      
        with: 
          payload-file-path: ../resources/other_layer.json
        env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
