on:
  push:
    branches: '**'   # [ "main" ]
  pull_request:
    branches: '**'   # [ "main" ]

jobs:
  SendJSONData:

    runs-on: ubuntu-latest
    
    steps:
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: '#general'
          # This data can be any valid JSON from a previous step in the GitHub Action
          
          payload: |
            	 {
                "text": "Code coverage Report below 95 percent",
                "blocks": [
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "below < 95 percent"
                    }
                  }
                ]
              }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
