on:
  push:
    branches: '**'   # [ "main" ]
  pull_request:
    branches: '**'   # [ "main" ]

jobs:
  integration_test_file_payload:
    runs-on: ubuntu-latest
    steps:
    - uses: slackapi/slack-github-action@v1.24.0
    - run: npm ci && npm run build
    - name: Dump out GitHub Context
      run: echo $JSON
      env:
        JSON: ${{ toJSON(github) }}
    - name: Post message to Slack with Payload path
      id: slackPayloadFile
      uses: ./
      with:
        payload-file-path: ./.github/workflow/small_payload.json
      
      env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
