on:
  push:
    branches: '**'   # [ "main" ]
  pull_request:
    branches: '**'   # [ "main" ]

jobs:
  SendJSONData:

    runs-on: ubuntu-latest
    
    steps:
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          # This data can be any valid JSON from a previous step in the GitHub Action
          # payload: |
          run: |
            curl -X POST --data-urlencode "payload={\"channel\": \"#general\", \"username\": \"bot\", \"text\": \"This is posted to #general and comes from a bot named bot.\", \"icon_emoji\": \":rocket:\"}" https://hooks.slack.com/services/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
            
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
