# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

# name: Learning Slack Notify from Github Actions 01
# channelId: "C05L0RYE6MT"
on:
  push:
    branches: '**'   # [ "main" ]
  pull_request:
    branches: '**'   # [ "main" ]

jobs:
  slack:

    runs-on: ubuntu-latest
    
    steps:

      - uses: pullreminders/slack-action@master
        env:
          # required
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_SECRET_KEY }}
        with:
          # custom message to send to slack
         args: '{\"channel\":\"C05L0RYE6MT\",\"blocks\":\"text\":\"SK :rocket:\"}'
         
        # Pick up events even if the job is success.
        if: success()
