# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

# name: Learning Slack Notify from Github Actions 01
# channelId: "C05L0RYE6MT"
on:
  push:
    branches: '**'   # [ "main" ]
  pull_request:
    branches: '**'   # [ "main" ]

jobs:
  slack:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Notify slack
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_SECRET_KEY }}
        SLACK_COLOR: '#3278BD'
        SLACK_ICON: https://upload.wikimedia.org/wikipedia/commons/6/68/NoxttonBot.png?size=48
        SLACK_MESSAGE: 'Post Content :rocket:'
        
      uses: pullreminders/slack-action@master
      with:
       args: '{\"channel\":\"C05L0RYE6MT\",\"blocks\": \"text\":\"*Hello* :rocket: world from SK\"}'
    #status: ${{ job.status }}
    #version: '1.0.0'
    #platform: 'Android'
    #channel: '#workflows'
