# Name of workflow to be displayed on GitHub Console
# name: Test Slack Notification

# Triggers the workflow on separate events
on:
  push:
    # Trigger the workflow on push event for all branches
    branches:
      -  '**'
  pull_request:
    # Trigger the work flow on pull request event for main branch
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # "notify" workflow for slack notification
  notify:

    name: Notify on Slack -Github details
    runs-on: ubuntu-latest
      # Only run this workflow when "build" workflow succeeds
      # needs: [build]

    # Only run this workflow if it target is main branch on pull_request event
    if: ${{ github.base_ref == 'main' && github.event_name == 'pull_request' }}

    steps:

      - uses: pullreminders/slack-action@master
        env:
          # required
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          # custom message to send to slack
          # args: '{\"channel\":\"C05L0RYE6MT\", \”blocks\”: [{\”type\”: \”section\”,\”text\”: {\”type\”: \”mrkdwn\”,\”text\”: \”We found *205 Hotels* in New Orleans, LA from *12/14 to 12/17*\”},\”accessory\”: {\”type\”: \”overflow\”,\”options\”: [{\”text\”: {\”type\”: \“plain_text\”,\”emoji\”: true,\”text\”: \”Option One\”},\”value\”: \”value-0\”},{\”text\”: {\”type\”: \”plain_text\”,\”emoji\”: true,\”text\”: \”Option Two\”},\”value\”: \”value-1\”},{\”text\”: {\”type\”: \”plain_text\”,\”emoji\”: true,\”text\”: \”Option Three\”},\”value\”: \”value-2\”},{\”text\”: {\”type\”: \”plain_text\”,\”emoji\”: true,\”text\”: \”Option Four\”},\”value\”: \”value-3\”}]}},{\”type\”: \”divider\”},{\”type\”: \”section\”,\”text\”: {\”type\”: \”mrkdwn\”,\”text\”: "*<fakeLink.toHotelPage.com|Windsor Court Hotel>*\n★★★★★\n$340 per night\nRated: 9.4 - Excellent\”},\”accessory\”: {\”type\”: \”image\”,\”image_url\”: \”https://api.slack.com/img/blocks/bkb_template_images/tripAgent_1.png\”,\”alt_text\”: \”Windsor Court Hotel thumbnail\”}},{\”type\”: \”context\”,\”elements\”: [{\”type\”: \”image\”,\”image_url\”: \”https://api.slack.com/img/blocks/bkb_template_images/tripAgentLocationMarker.png\”,\”alt_text\”: \”Location Pin Icon\”},{\”type\”: \”plain_text\”,\”emoji\”: true,\”text\”: \”Location: Central Business District\”}]},{\\“type\”: \”divider\”},{\”type\”: \”section\”,\”text\”: {\”type\”: \”mrkdwn\”,\”text\”: \”*<fakeLink.toHotelPage.com|The Ritz-Carlton New Orleans>*\n★★★★★\n$340 per night\nRated: 9.1 - Excellent\”},\“accessory\“: {\“type\“: \“image\“,\“image_url\“: \“https://api.slack.com/img/blocks/bkb_template_images/tripAgent_2.png\”,\“alt_text\”: \”Ritz-Carlton New Orleans thumbnail\”}},{\”type\”: \”context\”,\”elements\”: [{\”type\”: \”image\”,\”image_url\”: \”https://api.slack.com/img/blocks/bkb_template_images/tripAgentLocationMarker.png\”,\”alt_text\”: \”Location Pin Icon\”},{\”type\”: \”plain_text\”,\”emoji\”: true,\”text\”: \”Location: French Quarter\”}]},{\”type\”: \”divider\”},{\”type\”: \”section\”,\”text\”: {\”type\”: \”mrkdwn\”,\”text\”: \”*<fakeLink.toHotelPage.com|Omni Royal Orleans Hotel>*\n★★★★★\n$419 per night\nRated: 8.8 - Excellent\”},\”accessory\”: {\”type\”: \”image\”,\”image_url\”: \”https://api.slack.com/img/blocks/bkb_template_images/tripAgent_3.png","alt_text": "Omni Royal Orleans Hotel thumbnail\”}},{\”type\”: \”context\”,\”elements\”: [{\”type\”: \”image\”,\”image_url\”: \”https://api.slack.com/img/blocks/bkb_template_images/tripAgentLocationMarker.png\”,\”alt_text\”: \”Location Pin Icon\”},{\”type\”: \”plain_text\”,\”emoji\”: true,\”text\”: \”Location: French Quarter\”}]},{\”type\”: \”divider\”},{\”type\”: \”actions\”,\”elements\”: [{\”type\”: \”button\”,\”text\”: {\”type\”: \”plain_text\”,\”emoji\”: true,\”text\”: \”Next 2 Results\”},\”value\”: \”click_me_123\”}]}]}'
          args: '{\"channel\":\"C05L0RYE6MT\",\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Pull Request:* ${{ github.event.pull_request.title }}\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Contributor :* ${{ github.event.pull_request.user.login }}\n*Request State:* ${{ github.event.pull_request.state }}\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"<${{ github.event.pull_request.html_url }}|View Pull Request>\"}}]}'

        # Pick up events even if the job is success.
        if: success()
